name: flutter_park_plugin
description: A new Flutter package for Mini Park App.
version: 0.0.1
author: Bhagat Singh (Bhagat8533)
homepage: https://github.com/bhagat-opskube/flutter_park_plugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.1"

dependencies:
  flutter:
    sdk: flutter
  #  appmetrica_sdk: ^0.0.6
  #  flutter_linkify: ^5.0.0
  #  url_launcher: ^6.0.3
  dio: ^3.0.10
  package_info: ^2.0.0
  flutter_svg: ^0.21.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - packages/flutter_park_plugin/assets/images/flight.svg
    - packages/flutter_park_plugin/assets/images/park_circle.svg
    - packages/flutter_park_plugin/assets/images/park.svg
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Segoe
      fonts:
        - asset: packages/flutter_park_plugin/assets/fonts/Segoe-Regular.ttf
        - asset: packages/flutter_park_plugin/assets/fonts/Segoe-Light.ttf
          weight: 300
        - asset: packages/flutter_park_plugin/assets/fonts/Segoe-SemiBold.ttf
          weight: 500
        - asset: packages/flutter_park_plugin/assets/fonts/Segoe-SemiBold.ttf
          weight: 600
        - asset: packages/flutter_park_plugin/assets/fonts/Segoe-Bold.ttf
          weight: 700
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
